### ISSUE TITLE
Democratic-co different classifiers

### ISSUE THREAD

**Issue by alvarag** [dpr1005/Semisupervised-learning-and-instance-selection-methods#151]
I have been reviewing the Democratic-co learning algorithm implementation and I think the three classifiers to use should be parametrizable, i.e., the user should be able to change them.

**Comment by dpr1005** [comment]
Sounds like an appropriate enhancement

**Comment by alvarag** [comment]
And the same with the tri-training: instead of giving a fixed possibilities of classifiers, it should be better if the user can select any of Scikit-learn classifiers.

**Comment by alvarag** [comment]
And only one more issue: Add the original citation on a comment at the beginning of the code (such as you did on Democratic-co).

Thanks

**Comment by dpr1005** [comment]
Based on current comments, Democratic Co-Learning and Tri-Training could be parametrized as desired in terms of classifiers to use. Co-Training should be too, shouldn't it? @alvarag
