### ISSUE TITLE
Annex - Technical Programming Documentation

### ISSUE THREAD

**Issue by dpr1005** [dpr1005/Semisupervised-learning-and-instance-selection-methods#157]
TPD Sections
------------
- [x] #158
- [x] #159
- [x] #160
- [x] #161
- [x] #179

Extra 
-----
- [x] #199

**Comment by alvarag** [comment]
Come comments about the documentation:

[memoriaAAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8426313/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8426314/anexosAAG.pdf)

**Comment by dpr1005** [comment]
Really appreciate it @alvarag. When I am done with #159 I will look into it.

**Comment by alvarag** [comment]
[anexosAAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8619321/anexosAAG.pdf)
More comments on the pdf files:
[memoriaAAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8619320/memoriaAAG.pdf)

**Comment by dpr1005** [comment]
I will look into them later this week, thanks in advance for your comments
