### ISSUE TITLE
Create Rank-Based Statistics 

### ISSUE THREAD

**Issue by dpr1005** [dpr1005/Semisupervised-learning-and-instance-selection-methods#218]

**Comment by alvarag** [comment]
Try to use this tool, it looks perfect for what we are looking for
https://www.theoj.org/joss-papers/joss.02173/10.21105.joss.02173.pdf

Regarding statistical tests, if you have time and you want to learn I have found these slides from Granada's Professors (Salva and Paco) that are pretty dense but quite informative. There are A LOT! Be careful with them ;)
https://sci2s.ugr.es/sites/default/files/files/TutorialsAndPlenaryTalks/INIT-AERFAI-Course-Statistical_Analysis_of_Experiments.pdf

**Comment by dpr1005** [comment]
I will look into it later today, thanks @alvarag!

**Comment by dpr1005** [comment]
https://github.com/hfawaz/cd-diagram

**Comment by alvarag** [comment]
Yo creo que lo mejor va a ser usar los propios de Scikit-learn, pero tengo que revisarlo bien para hacerte un ejemplo "digerible":

https://github.com/maximtrp/scikit-posthocs

**Comment by dpr1005** [comment]
I have been looking around for them, but could not find anything, I guess my Googling skills are not as on point as I thought.

Anyway, I appreciate it, when a demo or similar is ready let me know. In the meantime I will keep trying to figure it out which rank implementation is OK to work with using the Keel application.

Thanks @alvarag!
