### ISSUE TITLE
Minor documentation comments

### ISSUE THREAD

**Issue by alvarag** [dpr1005/Semisupervised-learning-and-instance-selection-methods#229]
[anexosAAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8698635/anexosAAG.pdf)
[memoria_AAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8698636/memoria_AAG.pdf)

**Comment by dpr1005** [comment]
Thanks @alvarag! I will look into it later this week
