### ISSUE TITLE
Improvements on experimental section

### ISSUE THREAD

**Issue by alvarag** [dpr1005/Semisupervised-learning-and-instance-selection-methods#238]
[memoria_AAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8737580/memoria_AAG.pdf)

**Comment by dpr1005** [comment]
I will get back to you via email when the changes are done. Thanks @alvarag!

**Comment by alvarag** [comment]
I have identified several issues that was in the previous pdf that are still here... maybe you passed by some of my comments on the previous version?

Check it please.

[memoria.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/8760459/memoria.pdf)
