### ISSUE TITLE
Comments on Related works

### ISSUE THREAD

**Issue by alvarag** [dpr1005/Semisupervised-learning-and-instance-selection-methods#81]
[memoriaAAG.pdf](https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/files/7935915/memoriaAAG.pdf)

**Comment by dpr1005** [comment]
There is a couple things I would like to discuss with you (@alvarag) in tomorrow's meeting, related to the Related woks of the report.

**Comment by alvarag** [comment]
Perfect, we'll discuss it tomorrow
