### ISSUE TITLE
Reformat csv reading and plot the number of instances being used throughout the hypothesis validation process

### ISSUE THREAD

**Issue by dpr1005** [dpr1005/Semisupervised-learning-and-instance-selection-methods#84]
The basic idea is to add a new metric on the right of the current plot. A handmade of the desired result is the following.
![Captura de pantalla 2022-01-26 a las 10.45.43.png](https://images.zenhubusercontent.com/5faa432047203bbd7dd5c5fa/551bfe55-dc5a-421e-a63b-b89d9a391cf4)

**Comment by dpr1005** [comment]
The desired result has been achieved
![Dataset_iris_accuracy score_with_deletion](https://user-images.githubusercontent.com/74184545/151406527-e9689c15-02d7-497a-83af-cae3742d97bd.png)

**Comment by dpr1005** [comment]
You mean on the right legend, is that correct?

**Comment by dpr1005** [comment]
Something like this @alvarag?
![Dataset_14_banana_norm_f1_with_deletion](https://user-images.githubusercontent.com/74184545/151409728-cec2df70-3dc9-45e0-8599-3e744b8ed689.png)

**Comment by alvarag** [comment]
Yes, that is what I wanted to see. The problem is that ENN is fitlering instances of the original dataset, thus it is worsening the performance

**Comment by dpr1005** [comment]
Yeah, I knwon, in the following picture you can see the same experiment without deletion of the originl dataset instances. Thus the performance improves quite a bit
![Dataset_14_banana_norm_f1_without_deletion](https://user-images.githubusercontent.com/74184545/151410632-d332f083-4e75-4283-a56c-518775cd9de6.png)

**Comment by dpr1005** [comment]
Nevertheless, both the "Banana" and the "Iris" datasets have been used as tests to check that all the code worked correctly. I am currently running the experimentation on all the datasets we have in order to have a wider range of results.
